name = 'Paged-mod'
license = 'MIT'
# licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
# homepage = 'https://github.com/owner/repo'

# Taxonomy terms
tags = ['blog', 'minimal', 'clean', 'light']
features = ['blog']

# If the theme has a single author
[author]
  name = 'Chenke Qiu'
# homepage = 'Your website'

# If porting an existing theme
[original]
  name = "Yihui Xie"
  homepage = "https://yihui.org"
  repo = 'https://github.com/yihui/hugo-paged'
